import AppWrapper from "@/utils/AppWrapper";



export const metadata = {
  title: "SagaMusic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" style={{ scrollBehavior: "smooth" }}>
      <body>
        <AppWrapper>
          {children}
        </AppWrapper>
      </body>
    </html>
  );
}
